### ISSUE TITLE
[NixOS] Build error

### ISSUE THREAD

**Issue by IceDBorn** [amadejkastelic/Hyprlux#3]
I followed your instructions and I get this when trying to rebuild.

```nix
error: The option 'home' does not exist. Definition values:
       - In '/nix/store/hymxvvxlm7vldqjhlhhxg48rl52r5pfp-source/system/desktop/hyprland/modules/hyprlux.nix'
```

Probably related to [this](https://github.com/amadejkastelic/Hyprlux/blob/66a7f829261f1202738fd3b02a9aef47a4a75d58/module.nix#L105).

**Comment by amadejkastelic** [comment]
Can you try using it as a hm module?

**Comment by amadejkastelic** [comment]
@IceDBorn I've split up the home manager module and nixos module. Can you try this branch: https://github.com/amadejkastelic/Hyprlux/pull/4?

**Comment by IceDBorn** [comment]
@amadejkastelic I'll try testing it out later today. I'm sorry, working right now.

**Comment by IceDBorn** [comment]
Using the [hm-module](https://github.com/amadejkastelic/Hyprlux/pull/4) branch and this module file:

```nix
{ inputs, ... }:

{
  imports = [
    inputs.hyprlux.nixosModules.default
  ];

  programs.hyprlux = {
    enable = true;

    night_light = {
      enabled = true;
      start_time = "21:00";
      end_time = "07:00";
      temperature = 3500;
    };

    vibrance_configs = [
      {
        window_class = "cs2";
        window_title = "";
        strength = 100;
      }
    ];
  };
}
```

Results in 
```nix
    error: The option `xdg.configFile' does not exist. Definition values:
       - In `/nix/store/r6kx2cs4dcqq5czqxibpf9rnqdy1swfg-source/system/applications/modules/hyprlux.nix':
           {
             _type = "if";
             condition = true;
             content = {
               "hypr/hyprlux.toml" = {
           ...
```

**Comment by IceDBorn** [comment]
There is no `xdg.configFile` on NixOS, you need `home manager` for it. Doesn't `hyprlux` look at `/etc` for a config file? You can use the existing options to control the resulting file in `/etc/hyprlux/config.toml` for example. Like I do [here](https://github.com/IceDBorn/IceDOS/blob/7f2c76d1c3efe1833efacc278a6d83c82e5013cc/system/applications/modules/zed/options.nix#L57). I'm not sure if this is the best practice, but it would be enough for me.

**Comment by amadejkastelic** [comment]
I'll look into it.

**Comment by IceDBorn** [comment]
Is there a messaging platform you use? I would love to help with the matter.

**Comment by amadejkastelic** [comment]
Fixed in https://github.com/amadejkastelic/Hyprlux/pull/4
